from pathlib import Path
from dataclasses import dataclass

import librosa
import numpy as np
import soundfile as sf
import torch
from demucs.apply import apply_model
from demucs.pretrained import get_model


@dataclass(frozen=True)
class StemSeparationResult:
    model_name: str
    requested_device: str
    used_device: str
    stem_paths: dict[str, Path]
    stem_metadata: dict[str, dict[str, str | float]]


def _resolve_torch_device(device_preference: str) -> tuple[torch.device, str]:
    preference = device_preference.strip().lower()
    if preference == "cpu":
        return torch.device("cpu"), "cpu"

    has_cuda = bool(torch.cuda.is_available())
    if preference == "gpu":
        return (torch.device("cuda"), "cuda") if has_cuda else (torch.device("cpu"), "cpu")

    return (torch.device("cuda"), "cuda") if has_cuda else (torch.device("cpu"), "cpu")


def expected_stems_for_model(model_name: str) -> list[str]:
    if model_name == "htdemucs_6s":
        return ["drums", "bass", "vocals", "other", "piano", "guitar"]
    return ["drums", "bass", "vocals", "other"]


def _load_audio_for_model(audio_path: Path, sample_rate: int, channels: int) -> torch.Tensor:
    waveform, _ = librosa.load(str(audio_path), sr=sample_rate, mono=False)

    if waveform.ndim == 1:
        waveform = waveform[np.newaxis, :]

    if channels == 1 and waveform.shape[0] > 1:
        waveform = np.mean(waveform, axis=0, keepdims=True)
    elif channels > 1 and waveform.shape[0] == 1:
        waveform = np.repeat(waveform, channels, axis=0)
    elif channels > 1 and waveform.shape[0] > channels:
        waveform = waveform[:channels, :]

    return torch.tensor(waveform, dtype=torch.float32)


def separate_audio_stems(
    audio_path: Path,
    output_dir: Path,
    model_name: str = "htdemucs_6s",
    device_preference: str = "auto",
) -> StemSeparationResult:
    output_dir.mkdir(parents=True, exist_ok=True)

    requested_model = model_name
    try:
        model = get_model(model_name)
    except Exception:
        if model_name != "htdemucs":
            model_name = "htdemucs"
            model = get_model(model_name)
        else:
            raise RuntimeError("Source separation failed: unable to load Demucs model")

    torch_device, used_device = _resolve_torch_device(device_preference)
    model.to(torch_device)
    model.eval()

    mix = _load_audio_for_model(audio_path, model.samplerate, model.audio_channels)

    fallback_reason: str | None = None
    try:
        with torch.no_grad():
            estimates = apply_model(
                model,
                mix[None],
                shifts=1,
                split=True,
                overlap=0.25,
                progress=False,
                device=torch_device,
            )[0]
    except Exception as first_error:
        if used_device != "cuda":
            raise

        fallback_reason = str(first_error)
        cpu_device = torch.device("cpu")
        try:
            model.to(cpu_device)
            with torch.no_grad():
                estimates = apply_model(
                    model,
                    mix[None],
                    shifts=1,
                    split=True,
                    overlap=0.25,
                    progress=False,
                    device=cpu_device,
                )[0]
            used_device = "cpu"
        except Exception as second_error:
            raise RuntimeError(
                f"Source separation failed on CUDA and CPU fallback. CUDA error: {first_error}; CPU error: {second_error}"
            ) from second_error

    stem_root = output_dir / model_name / audio_path.stem
    stem_root.mkdir(parents=True, exist_ok=True)

    expected = set(expected_stems_for_model(model_name))
    stems: dict[str, Path] = {}
    for stem_index, stem_name in enumerate(model.sources):
        if stem_name not in expected:
            continue
        stem_audio = estimates[stem_index].cpu().numpy().T
        output_path = stem_root / f"{stem_name}.wav"
        sf.write(str(output_path), stem_audio, model.samplerate)
        stems[stem_name] = output_path

    if not stems:
        raise RuntimeError("No stems generated by source separation")

    stem_metadata: dict[str, dict[str, str | float]] = {}
    for stem_name, stem_path in stems.items():
        audio, _ = librosa.load(str(stem_path), sr=model.samplerate, mono=True)
        rms = float(np.sqrt(np.mean(np.square(audio)))) if audio.size else 0.0
        stem_metadata[stem_name] = {
            "path": str(stem_path),
            "source_model": model_name,
            "requested_model": requested_model,
            "requested_device": device_preference.strip().lower() or "auto",
            "used_device": used_device,
            "rms_energy": rms,
        }
        if fallback_reason:
            stem_metadata[stem_name]["device_fallback"] = "cuda_to_cpu"
            stem_metadata[stem_name]["fallback_reason"] = fallback_reason[:500]

    return StemSeparationResult(
        model_name=model_name,
        requested_device=device_preference.strip().lower() or "auto",
        used_device=used_device,
        stem_paths=stems,
        stem_metadata=stem_metadata,
    )